### ISSUE TITLE
Add continuous integration using Travis

### ISSUE THREAD

**Issue by rootatkali** [kfaryarok/ABUELA#1]
Runs tests and builds every PR/push

**Comment by rootatkali** [comment]
In order to add CI support, we have to make this project public. @Xiddoc @AvivHavivyan what do you think?

**Comment by Xiddoc** [comment]
> In order to add CI support, we have to make this project public. @Xiddoc @AvivHavivyan what do you think?

Sounds awesome. Aren't you the one always rambling about open source? 🤣😉

**Comment by rootatkali** [comment]
Repo is now public

**Comment by rootatkali** [comment]
https://travis-ci.org/github/kfaryarok/ABUELA/ Closing.
